<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>MobileMTPBackup</AssemblyName>
    <RootNamespace>MobileMTPBackup</RootNamespace>
    <RuntimeIdentifier>win-x64</RuntimeIdentifier>
    <SelfContained>true</SelfContained>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishTrimmed>false</PublishTrimmed>
    <Version>4.7.0</Version>
    <AssemblyVersion>4.7.0.0</AssemblyVersion>
    <FileVersion>4.7.0.0</FileVersion>
  </PropertyGroup>
</Project>
